# Generated by Django 4.2 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_industry_movie_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
