# Generated by Django 4.2 on 2025-05-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_backdrop_path_alter_movie_poster_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecast",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moviecast_set",
                to="movies.person",
            ),
        ),
        migrations.AlterField(
            model_name="moviecrew",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moviecrew_set",
                to="movies.person",
            ),
        ),
    ]
