# Generated by Django 4.2 on 2025-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_moviecast_person_alter_moviecrew_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["tmdb_id"], name="movies_movi_tmdb_id_0e4cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title", "release_date"], name="movies_movi_title_20a8c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                fields=("tmdb_id",), name="unique_tmdb_id"
            ),
        ),
    ]
