# Generated by Django 4.2 on 2025-05-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_tmdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
